config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :cards, only: [:show, :index] do
    collection { post :import }
  end
  resources :expansions, only: [:show, :index] do
    collection { post :import }
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :expansion
  has_one :price
  def self.import
  # def self.import(file)
    # CSV.foreach(file.path, headers: true, skip_blanks: true) do |row|
    CSV.foreach('cards.csv', headers: true, skip_blanks: true) do |row|
      card_hash = row.to_hash
      expansion = Expansion.find_by_name_en(row["expansion"])
      card = find_by_id(row["id"]) || new
      card.attributes = card_hash.except("expansion")
      card.expansion = expansion
      card.save!
      format_fields(card)
    end
  end

  def self.format_fields(card)
    name_en = card.name_en
    name_en = name_en.gsub(/(?<=[a-z])(?=[A-Z])/, ' ')
    name_en = name_en.gsub('Mega ','M ') if card.name_en.include?("EX")
    number = card.number.strip
    rarity = card.rarity.gsub(/(?<=[a-z])(?=[A-Z])/, ' ')
    if card.card_type.nil?
      arr = @@type_map.assoc(card.type_element)
      if card.type_element.ends_with? "E"
        type_element = card.type_element.gsub(" E","")
        card.update(number:number, name_en:name_en, rarity: rarity,
                    type_element: type_element, card_type: "Energy")
      elsif arr.nil?
        card.update(number:number, name_en:name_en, rarity: rarity,
                    card_type: "Pokémon")
      else
        card.update(number:number, name_en:name_en, rarity: rarity,
                    type_element: arr[1], card_type: arr[2])
      end
    end
  end

  @@type_map = [
    ["I","Item","Trainer"],
    ["Su","Supporter","Trainer"],
    ["St","Stadium","Trainer"],
    ["T","Trainer","Trainer"],
    ["T [GC]","Goldenrod Game Corner","Trainer"],
    ["T [R]","Trainer","Trainer"],
    ["T [St]","Stadium","Trainer"],
    ["T [Su]","Supporter","Trainer"],
    ["T [TM]","TM","Trainer"],
    ["T [Tool]","Tool","Trainer"]
  ]
end

app/models/card_price.rb
class CardPrice < ActiveRecord::Base
  belongs_to :card
end

app/models/expansion.rb
class Expansion < ActiveRecord::Base
  has_many :cards
  # def self.import(file)
  #   CSV.foreach(file.path, headers: true, skip_blanks: true) do |row|
  def self.import(file)
    CSV.foreach(file, headers: true, skip_blanks: true) do |row|
      expansion_hash = row.to_hash
      expansion = find_by_id(row["id"]) || new
      expansion.attributes = expansion_hash
      expansion.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show]

  def show
    @card_prices = CardPrice.where(card: @card).order(:price)
    @expansion = @card.expansion
  end

  def index
    @cards = Card.all.order(:expansion_id).order(:id)
    @prices = CardPrice.all
  end

  def import
    begin
      Card.import
      # Card.import(params[:file])
      redirect_to root_url, notice: "Cards imported."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end
end

app/controllers/expansions_controller.rb
class ExpansionsController < ApplicationController
  before_action :set_expansion, only: [:show]
  def index
    Expansion.all
  end

  def import
    begin
      # Expansion.import(params[:file])
      file = File.join(Rails.root, 'app/assets/expansions.csv')
      Expansion.import(file)
      redirect_to root_url, notice: "Expansions imported."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end

  def show
  end

  private

  def set_expansion
    @expansion = Expansion.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/expansions_helper.rb
module ExpansionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/index.html.erb
<h1 class="ls-title-intro ls-ico-cart">Cartas</h1>
<section class="ls-form-horizontal" id="order_form">
  <!-- <div class="form-inputs">
    <label class="ls-label">
      <%= form_tag import_cards_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Importar Cartas" %>
      <% end %>
    </label>
  </div> -->
<%= button_to 'Import Cards', import_cards_path, method: :post %>
</section>
<hr>

app/views/cards/show.html.erb
<% if @card.name_pt %>
  <h1 class="ls-title-intro ls-ico-cart"><%= @card.name_en%> / <%= @card.name_pt%></h1>
<% else %>
  <h1 class="ls-title-intro ls-ico-cart"><%= @card.name_en%></h1>
<% end %>
<span>
  <%= image_tag(@card.photo, alt: @card.name_en, size: '235x330') %>
  <p><strong>Tipo:</strong> <%= @card.card_type %></p>
  <% if @card.card_type == "Pokemon" %>
    <p><strong>Elemento:</strong> <%= @card.type_element %></p>
  <% else %>
    <p><strong>Sub-tipo:</strong> <%= @card.type_element %></p>
  <% end %>
  <p><strong>Raridade:</strong> <%= @card.rarity %></p>
  <p><strong>Expansão:</strong> <%= @expansion.name_en %></p>
  <% @card_prices.each do |card_price| %>
    <p><%="Loja: #{card_price.shop_name} Preço: R$#{card_price.price} "+"Reverse Foil" if card_price.foil? %><p>
  <% end %>
</span>

app/views/expansions/index.html.erb
<h1 class="ls-title-intro ls-ico-cart">Expansões</h1>
<section class="ls-form-horizontal" id="order_form">
  <!-- <div class="form-inputs">
    <label class="ls-label col-md-3">
      <%= form_tag import_expansions_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Importar Expansões" %>
      <% end %>
    </label>
  </div> -->
  <%= button_to 'Import Expansions', import_expansions_path, method: :post %>
</section>

app/views/expansions/show.html.erb
<h1>Expansions#show</h1>
<p>Find me in app/views/expansions/show.html.erb</p>

app/views/home/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<html>
  <body>
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2015 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-light-red">
<head>
  <title>Planalto Indigo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag  'application' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="description" content="Sistema de Vendas CampusCode.">
  <link href="http://assets.locaweb.com.br/locastyle/3.8.2/stylesheets/locastyle.css" rel="stylesheet" type="text/css">
</head>
<body>
  <div class="ls-topbar ">

  <!-- Barra de Notificações -->
  <div class="ls-notification-topbar">
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>

  <%= link_to :back, class: 'ls-go-next' do %>
    <span class="ls-text">Voltar</span>
  <% end %>

  <!-- Nome do produto/marca com sidebar -->
  <h1 class="ls-brand-name">
    <a href="/" class="ls-ico-earth">
      <small>Descrição</small>
      Planalto Indigo
    </a>
  </h1>

  <!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
  </div>


  <aside class="ls-sidebar">

  <div class="ls-sidebar-inner">
    <a href="/locawebstyle/documentacao/exemplos//pre-painel"  class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>

    <nav class="ls-menu">
      <ul>
        <li><%= link_to 'Todas as cartas', cards_path, class: 'ls-ico-cog'%></li>
        <li><%= link_to 'Todas as expansões', expansions_path, class: 'ls-ico-cog'%></li>
      </ul>
    </nav>

  </div>
  </aside>

  <main class="ls-main ">
    <div class="container-fluid">
      <span class="ls-alert-warning col-xs-12"><%= flash[:alert] %></span>
      <span class="ls-alert-success col-xs-12"><%= flash[:notice] %></span>
      <%= yield %>
    </div>
  </main>

  <!-- We recommended use jQuery 1.10 or up -->
  <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="http://assets.locaweb.com.br/locastyle/3.8.2/javascripts/locastyle.js" type="text/javascript"></script>
</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Planalto Indigo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cartas<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Todas as Cartas", cards_path%></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Todas as Expansões", expansions_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>